/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutViewComponent: typeof import('./src/components/AboutViewComponent.vue')['default']
    AFormComponent: typeof import('./src/components/AFormComponent.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent.vue')['default']
    FormComponent: typeof import('./src/components/FormComponent.vue')['default']
    HomeViewComponent: typeof import('./src/components/HomeViewComponent.vue')['default']
    LayoutComponent: typeof import('./src/components/LayoutComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskTableComponent: typeof import('./src/components/TaskTableComponent.vue')['default']
    TaskViewComponent: typeof import('./src/components/TaskViewComponent.vue')['default']
  }
}
